### ISSUE TITLE
New default style: Columns break from 4+ to 2 to 1

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/hybrid-starter-theme#26]
Some very rough code that will need to get better integrated into the existing `columns.css` partial:

```css
/* For columns with 4 or more columns, switch to 2 columns between medium and large */
.wp-block-columns:has(.wp-block-column:nth-child(4)) {
	@include mq-max($bp--full) {
		flex-wrap: wrap !important;

		.wp-block-column {
			flex-basis: calc(50% - $gap) !important;
			margin-inline: 0 !important;
			flex-grow: 1;
		}

		& + & {
			margin-block-start: $gap;
		}
	}
	@include mq-max($bp--blocks) {
		.wp-block-column {
			flex-basis: calc(100%) !important;
		}
	}
}
```
