### ISSUE TITLE
Under consideration: add .is-root-container to any div that contains blocks

### ISSUE THREAD

**Issue by mrwweb** [mrwweb/hybrid-starter-theme#7]
This would make front- and back-end styles align more closely when needing to set rules that only impact top-level blocks.

**Comment by mrwweb** [comment]
A rule that would benefit from this:

```css
.is-root-container > .wp-block-group.alignfull:not(.has-background),
.is-root-container > .wp-block-columns.alignfull:not(.has-background) {
	max-width: 90%;
	margin-inline: auto;
}
```
